### ISSUE TITLE
install-parity.sh: PARITY_DEB_URL does not use HTTPS

### ISSUE THREAD

**Issue by bananer** [paritytech/scripts#12]
line 4:
`PARITY_DEB_URL=http://d1h4xl4cr1h0mo.cloudfront.net/v${PARITY_VERSION}/x86_64-unknown-linux-gnu/parity_${PARITY_VERSION}_amd64.deb`

later:
`		curl -L $PARITY_DEB_URL > $file`
`		sudo dpkg -i $file`

I'd really rather not install packages form an insecure connection. Changing the url to use https seems to work, so maybe that's a really quick fix.

**Comment by arkpar** [comment]
Fixed. Thanks for the suggestion.
