### ISSUE TITLE
install failed on macos

### ISSUE THREAD

**Issue by doowb** [paritytech/scripts#19]
I was following the instructions on the main README and when I got to the point to download and run the install script, I received the following error:

```sh
installer: Error the package path specified was invalid: '/parity-1.8.2-macos-installer.pkg'.
```

I tracked it down to the `mktemp -d` command returning an empty string in [this script](https://github.com/paritytech/scripts/blob/master/get-parity.sh#L92).

I found the downloaded installer package in my home directly and was able to run the command for darwin to finish the install.

I'm not sure how to go about trying to fix the script and testing it, but wanted to open the issue in case anyone else has an idea.

This was on `OS X Yosemite Version 10.10.5`

**Comment by 5chdn** [comment]
@doowb what happens if your run `mktemp -d` manually?

**Comment by doowb** [comment]
@5chdn I just get usage information:

![screen shot 2018-01-26 at 3 11 29 pm](https://user-images.githubusercontent.com/995160/35458748-94f6ab36-02ab-11e8-80a6-ce8adb670a49.png)

**Comment by 5chdn** [comment]
Please upgrade your macos. mktemp -d should create a temporary directory.
