### ISSUE TITLE
One liner should use `*-release` from vanity service

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/scripts#20]
Currently it fetches for instance from `stable` which may contain a newer, yet unreleased version.

**Comment by 5chdn** [comment]
For some weird reason, stable-release does not contain any builds:

https://vanity-service.parity.io/parity-binaries?format=markdown&version=stable-release

**Comment by 5chdn** [comment]
honestly, we should hard-code the release strings. I am having a hard time to understand why there is no stable-release in vanity, and why beta-release is serving 1.9.1 instead of 1.9.2 even though the tag is correctly placed.

**Comment by 5chdn** [comment]
cc @fevo1971 

1. please find out why beta-release tag is pointing to 1.9.1
2. please find out why stable-release tag is not built at all
