### ISSUE TITLE
Review get-substrate.sh Script

### ISSUE THREAD

**Issue by danforbes** [paritytech/scripts#218]
According to @bkchr, the get-substrate.sh script is likely very out-of-date. It may be worth reevaluating its value and soundness. For starters, notice that the following line installs `git` twice:
https://github.com/paritytech/scripts/blob/master/get-substrate.sh#L35

**Comment by danforbes** [comment]
See here for more discussion https://github.com/paritytech/polkadot/pull/1479

**Comment by riusricardo** [comment]
> According to @bkchr, the get-substrate.sh script is likely very out-of-date. It may be worth reevaluating its value and soundness. For starters, notice that the following line installs `git` twice:
> https://github.com/paritytech/scripts/blob/master/get-substrate.sh#L35

I remember that some VMs don't have git as default deployment. This is why it is part of the packages, it won't do a thing if it is already installed.

**Comment by riusricardo** [comment]
I agree with @bkchr, we should deprecate the script.

**Comment by danforbes** [comment]
Ricardo, other than Knowledge Base, Tutorials, Recipes and Node Template do we reference this script anywhere?

**Comment by danforbes** [comment]
I checked on the Polkadot Wiki and didn't see it there but admittedly I didn't look too hard.

**Comment by danforbes** [comment]
@joepetrowski do you know of any other places where the get-substrate.sh script may appear?

**Comment by riusricardo** [comment]
We should keep it in the repo and fix it but stop referencing and encouraging it. IMO, we don't want to break workshops/videos that used this method.

**Comment by thiolliere** [comment]
when latest rust nightly breaks substrate this script will fail, when this happens some ppl have no clue how to go from it.

At least when case cargo build fails, we should print a message pointing to some url which explains the complete process to install substrate.

(Also we could improve by setting a specific nightly toolchain but then we should make some CI to be sure this nightly doesn't get too old, but I would rather deprecate with some more message for ppl stuck)

**Comment by TriplEight** [comment]
FWIW it makes sense to test this script nightly in CI.
And btw, why it's still here and not in the substrate repo?

**Comment by riusricardo** [comment]
> And btw, why it's still here and not in the substrate repo?

@TriplEight We are deprecating the script. @thiolliere suggestions are good and we should print information stating this and  where they should find the latest installation instructions.

**Comment by NukeManDan** [comment]
I have #253 opened for those interested in updating/improving/expanding 🤞🏼 this script

**Comment by rcny** [comment]
Closing as stale.
