### ISSUE TITLE
One-liner downloads SHA256 file instead of actual installer on MacOS

### ISSUE THREAD

**Issue by keithmattix** [paritytech/scripts#28]
When I try to install parity with the one-liner, the actual file downloaded to my machine is parity_1.9.3_macos_macos.pkg.sha256 instead of the actual pkg file, so the installer is failing. On [this line](https://github.com/paritytech/scripts/blob/master/get-parity.sh#L64), the script selects the second index from the cut command, but based on the output I'm getting in my console for the value of `$MD`, it should be selecting the 3rd index via `-f3`.

![screen shot 2018-02-28 at 2 23 43 am](https://user-images.githubusercontent.com/1531662/36777260-7999749e-1c2e-11e8-8ac6-db8925a2c597.png)

**Comment by 5chdn** [comment]
@ddorgan @fevo1971 what's the status of removing sha256 from vanity?

**Comment by 5chdn** [comment]
fixed in #29
