### ISSUE TITLE
Why not use cachepot instead of sccache

### ISSUE THREAD

**Issue by woss** [paritytech/scripts#329]
Cachepot is under paritytech already and i am using it as a sccache replacement and works OK. Why still keep the sccache in the build process and docker images?

**Comment by TriplEight** [comment]
AFAIK `cachepot` is not much different from `sccache` when executed locally, by far.
But it is being developed for CI usage, and as soon as it's ready, it'll be introduced here.
Currently `cachepot` is not a priority project so no timelines, sorry.

**Comment by woss** [comment]
no probs, as i said i am using a modified image with the cachepot for the CI already.
