### ISSUE TITLE
Error in rustup update nightly

### ISSUE THREAD

**Issue by CatarinaPedreira** [paritytech/scripts#339]
I have a Dockerfile whose parent image is paritytech/ci-linux:974ba3ac-20201006.

When trying to build my dockerfile, the command "RUN rustup update nightly" yields the following error:

`=> ERROR [ 8/12] RUN rustup update nightly                                                                                                                     
------
 > [ 8/12] RUN rustup update nightly:
#11 8.878 info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
#11 10.69 info: latest update on 2021-09-13, rust version 1.57.0-nightly (51e514c0f 2021-09-12)
#11 10.73 info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
#11 14.32 info: downloading component 'cargo'
#11 16.20 info: downloading component 'rust-std'
#11 21.47 info: downloading component 'rustc'
#11 32.63 info: removing previous version of component 'rust-std' for 'wasm32-unknown-unknown'
#11 43.67 info: rolling back changes
#11 43.67 error: could not rename component file from '/usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-unknown-unknown/lib' to '/usr/local/rustup/tmp/p3ccm91_ff8xhqyw_dir/bk'
#11 43.67 error: caused by: other os error
#11 43.68 error: backtrace:
#11 43.68 error:    0: error_chain::backtrace::imp::InternalBacktrace::new
#11 43.68    1: rustup::utils::utils::rename
#11 43.68    2: rustup::dist::component::transaction::Transaction::remove_dir
#11 43.69    3: rustup::dist::component::components::Component::uninstall
#11 43.69    4: rustup::dist::manifestation::Manifestation::update
#11 43.69    5: rustup::dist::dist::update_from_dist_
#11 43.69    6: rustup::install::InstallMethod::install
#11 43.69    7: rustup::toolchain::DistributableToolchain::install_from_dist
#11 43.69    8: rustup::cli::rustup_mode::update
#11 43.69    9: rustup::cli::rustup_mode::main
#11 43.69   10: rustup_init::main
#11 43.69   11: std::rt::lang_start_internal::{{closure}}::{{closure}}
#11 43.69              at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:52
#11 43.69       std::sys_common::backtrace::__rust_begin_short_backtrace
#11 43.69              at rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys_common/backtrace.rs:130
#11 43.69   12: main
#11 43.69   13: __libc_start_main
#11 43.69   14: <unknown>
#11 43.69 
------
executor failed running [/bin/sh -c rustup update nightly]: exit code: 1
`

I'm aware this is a problem of compatibility between rustup and docker (the problem lies in the rename() function, more specifically in the fact that docker's filesystem behavior and rustup filesystem's behavior are not compatible) , as per https://github.com/rust-lang/rustup/issues/2542. 

The only suggested workaround so far is uninstalling and reinstalling rustup in its entirety, but it seems that nightly already tries to install the most recent version (1.57.0-nightly (51e514c0f 2021-09-12)), so I'm not sure why that works.

Do you have any idea can I go about this in a different way?

**Comment by rcny** [comment]
Closing as stale.
