### ISSUE TITLE
Inconsistencies between docs and get-parity.sh

### ISSUE THREAD

**Issue by ansermino** [paritytech/scripts#36]
In the setup documentation it states  `you won’t get the cutting edge features` from the bash script however it appears to be installing the latest beta version while I would expect it to be installing a stable release. 

It also goes on to say `this script will also offer to install the Netstats client and connect it to ethstats.net` but this appears to be implemented in the `install-deps.sh` script which is not referenced in the `get-parity.sh` script and no such prompt is given. Working on confirming the `install-deps.sh` in addition to the `get-parity.sh` would successfully setup netstats.

**Comment by 5chdn** [comment]
where do you read this?

**Comment by ddorgan** [comment]
@ansermino thanks for bringing this up. Yes it looks like the documentation isn't up to date and needs a review.

@5chdn https://wiki.parity.io/Setup

**Comment by 5chdn** [comment]
moved
