### ISSUE TITLE
get-parity.sh fails to upgrade to 2.0.0 beta

### ISSUE THREAD

**Issue by ascjones** [paritytech/scripts#37]
Linux deb files are no longer published in 2.0.0 so it fails to set `$DOWNLOAD_FILE`. Here's the output with echoed variables:

```
Release selected is: beta
LOOKUP: 'https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&os=linux&version=beta-release'
LIBSSL: '10'
DOWNLOAD_FILE: ''
basename: missing operand
Try 'basename --help' for more information.
Existing version of parity: 1.11.6 is newer than the version you attempting to install: 
```

So it evaluates this branch https://github.com/paritytech/scripts/blob/master/get-parity.sh#L49 but the deb file does not exist: https://vanity-service.parity.io/parity-binaries?architecture=x86_64&format=markdown&os=linux&version=beta-release

**Comment by 5chdn** [comment]
duplicate of #31 actually, @fevo1971 has a working script already

**Comment by fevo1971** [comment]
the issue with *get-parity.sh*, no longer being able to determine the correct version
string of 'stable' and 'beta' release is taken care of. the (now required)
additional step of updating the version strings within the script is documented in
the release documentation (checklist).

**Comment by ascjones** [comment]
Confirm that this works now! Upgraded successfully to 2.0.0 on linux.
