### ISSUE TITLE
Excuting a binary on M1 according to instructions is not working for me

### ISSUE THREAD

**Issue by brunopgalvao** [paritytech/scripts#431]
At the very bottom of the [README](https://github.com/paritytech/scripts/blob/master/README.md), it says:

:warning: If you want to execute a binary on OS X pay attention that with docker it is compiled for Linux. So if want to run it you need to use something like:  
`cargoenvhere paritytech/contracts-ci-linux:production cargo run`

Can someone reproduce this or am I doing something wrong?

**Comment by rcny** [comment]
Closing as stale.
