### ISSUE TITLE
Image `awscli`: check for scheduled build

### ISSUE THREAD

**Issue by chevdor** [paritytech/scripts#528]
The image `awscli` returns a rather old version so I guess we don't rebuild/publish on schedule.

Our image currently return:
```
aws-cli/1.19.81 Python/3.6.13 Linux/5.15.49-linuxkit botocore/1.20.81
```

The latest aws cli reports:
```
aws-cli/2.10.3 Python/3.11.2 Darwin/22.3.0 source/x86_64 prompt/off
```

**Comment by chevdor** [comment]
I found a manual schedule in https://gitlab.parity.io/parity/mirrors/scripts/-/pipeline_schedules.
Is there a reason why we do not rebuild weekly/monthly ?

Do I break anything clicking the ▶️ button to rebuild a new version ?

**Comment by rcny** [comment]
> Is there a reason why we do not rebuild weekly/monthly ?

Automatic rebuilds weren't setup as there wasn't such a requirement. Do you need scheduled rebuilds here?

> Do I break anything clicking the ▶️ button to rebuild a new version ?

Nope, feel free to press the button.

**Comment by chevdor** [comment]
Unless exception I think it would make sense to rebuild all on schedule.
We could keep the last one with a tag.

The risk of not rebuilding is that no one ends up pressing the button and we endup with ancient image content (os + tool).

I did press the button so the image is a little fresher now, although aws cli is still in v1 for some reason.

**Comment by rcny** [comment]
`aws-cli` v2 is a separate package and the migration here should be done [manually](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html).

> Unless exception I think it would make sense to rebuild all on schedule.

Enabled nightly rebuilds for this image.
